# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'ContatosIP67' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

pod "TPKeyboardAvoiding"
pod "AFNetworking"

  # Pods for ContatosIP67

  target 'ContatosIP67Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end
